name: Build on release artifact 1

# Events that trigger this workflow
on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4

      - name: Download build environment 📥
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: build-env
          path: ${{ github.workspace }}

      - name: List directory contents
        run: 'ls -lhaR ~'

      - name: Import environment
        run: cat .build-env >> $GITHUB_ENV

      - name: Output received variables
        run: |
          echo "upload_url=${{ env.upload_url }}"
          echo "tag=${{ env.tag }}"
          echo "skipped=${{ env.skipped }}"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ./dist/artifact1.txt
          asset_name: artifact1.txt
          asset_content_type: text/plain
