name: Build on release

# Events that trigger this workflow
on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  build-and-upload:
    name: Build and upload
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Echo github.event
        run: echo ${{ toJson(github) }}
