name: Release

# Events that trigger this workflow
on: [workflow_dispatch]

jobs:
  conventional-release:
    name: Conventional Commit Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: ${{ github.actor }}
          git-user-email: '${{ github.actor }}@users.noreply.github.com'
          release-count: '0'
          skip-on-empty: 'false'

      - name: Create Release
        uses: actions/create-release@v1.1.4
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Save action output to build environment 🗜
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          echo "upload_url=${UPLOAD_URL}" >> ~/.build-env
          echo "tag=${RELEASE_TAG}" >> ~/.build-env
          echo "skipped=${RELEASE_SKIPPED}" >> ~/.build-env
        env:
          UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
          RELEASE_TAG: ${{ steps.changelog.outputs.tag }}
          RELEASE_SKIPPED: ${{ steps.changelog.outputs.skipped }}

      - name: Upload build environment 📤
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-env
          path: '~/.build-env'
          retention-days: 1
