name: Test

# Events that trigger this workflow
on: [push, pull_request]

jobs:
  simple-test:
    name: Do a simple test run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4

      - name: Test something
        run: echo "Tested!"
